SAAVY/magpie

- .gitignore
- README.md
- client/api.py
- client/constants.py
- client/response.py
- client/url_utils.py
> Validate URLs

- client/api.py
- client/constants.py
- client/response.py
- client/url_utils.py
- Fixing flow for metadata classes taking url content
- Adding url types
- Logic for instantiating scraper
#4
> Fixing Issue #4 - better code flow

- client/api.py
- client/scraper/general_metadata.py
- client/scraper/metadata.py
- client/scraper/wikipedia_metadata.py
- client/scraper/youtube_metadata.py
- client/url_utils.py
> Fix imports

- LICENSE.md
- README.md
> add LICENSE.md

- .travis.yml
- Makefile
- build.sh
- client/scraper/youtube_metadata.py
- install.sh
- requirements.txt
- setup.cfg
#12 #13 
uses make files and bash scripts to make sure code is correct
`make install` to install dependencies
`make build dev` to build and run dev env
`make build prod` to build and run prod env (currently no different than dev)
> Build and install script

- .travis.yml
- client/api.py
- requirements.txt
- test/client/test_api.py
#14 
Working with Travis CI build =)
> Test infra

- client/scraper/general_metadata.py
> Passing in the actual content rather than the response object

- client/scraper/wikipedia_metadata.py
- test/client/scraper/test_wikipedia_metadata.py
- Fixed the issue with some wikipedia pages showing the wrong data
> Wikipedia bug fix

- client/api.py
- client/api_handler.py
- client/constants.py
- client/response.py
- client/scraper/error_metadata.py
- client/scraper/general_metadata.py
- client/scraper/metadata.py
- client/scraper/wikipedia_metadata.py
- client/scraper/youtube_metadata.py
- client/url_utils.py
- requirements.txt
#31 
General Website (Buzzfeed):
YouTube:
Wikipedia:
> Changing json structure, adding a seperate file for api logic

- build.sh
- test/client/scraper/test_wikipedia_metadata.py
> fix that build script no longer catches unit test errors

- client/constants.py
- client/response.py
- client/scraper/dropbox_metadata.py
- client/scraper/metadata.py
- client/scraper/wikipedia_metadata.py
- client/scraper/youtube_metadata.py
- client/url_utils.py
Addreses Issues in : https://github.com/SAAVY/magpie/issues/39
#39 
domain_url: just the root website url
favicon: the favicon url of the site
images: images moved to images instead of media
some cleanup of code also done
> Added addtional fields in return json

- Makefile
- build.sh
- client/api_handler.py
- client/constants.py
- client/response.py
- client/scraper/drive_metadata.py
- client/scraper/dropbox_metadata.py
- client/scraper/error_metadata.py
- client/scraper/general_metadata.py
- client/scraper/metadata.py
- client/scraper/wikipedia_metadata.py
- client/scraper/youtube_metadata.py
- client/url_utils.py
Issues addressed: #47 #40 #38
- Support more errors (https://github.com/SAAVY/magpie/issues/47)
- Refactor url_utils code so that all metadata objects take care of their own http request
- fetch_site_data method created
- Issue: https://github.com/SAAVY/magpie/issues/40
- handled some error cases wikipedia & dropbox was going into
- support #something in urls (in this case, it just removed the #something)
-https://github.com/SAAVY/magpie/issues/38
> Major refactor of scraper code

- client/config.py
> remove api key

- client/constants.py
- client/response.py
- client/scraper/dropbox_metadata.py
- client/scraper/error_metadata.py
- client/scraper/metadata.py
- client/scraper/youtube_metadata.py
adds new api_query_url field for api queries
added try catch for checking for api response
youtube now does both api and scraping of header for content
resolves issue: #71
> resolves issue with media url return data

- client/api_handler.py
- client/scraper/error_metadata.py
- client/url_utils.py
> Fix api crash when giving a bad request url

- client/scraper/metadata.py
- client/url_utils.py
- test/client/test_url_utils.py
- make sure favicons with url /static/favicon.ico still works
- added unit tests
#46
> Validate image url (favicon)

- client/api_handler.py
- client/constants.py
- client/response.py
- client/scraper/drive_metadata.py
- client/scraper/dropbox_metadata.py
- client/scraper/file_metadata.py
- client/scraper/image_metadata.py
- client/scraper/metadata.py
- client/scraper/youtube_metadata.py
- client/url_utils.py
- test/client/scraper/test_image_metadata.py
- test/client/scraper/test_youtube_metadata.py
> Support direct image/file url

- test/client/scraper/test_wikipedia_metadata.py
@AliceYuan @samiyaakhtar please approve :P It's a very quick fix, and just want our build to pass again :)
> Fixing failing wikipedia test due to code refactor

- .coveragerc
- .gitignore
- .travis.yml
- build.sh
- requirements.txt
#95 Adding code coverage tests
> Add test coverage

- client/scraper/drive_metadata.py
- client/scraper/dropbox_metadata.py
- client/scraper/error_metadata.py
- client/scraper/metadata.py
- client/scraper/wikipedia_metadata.py
- client/scraper/youtube_metadata.py
- test/client/scraper/test_wikipedia_metadata.py
- test/client/scraper/test_youtube_metadata.py
> Revert "Remove beautiful soup + refactor metadata code"

- client/constants.py
- client/scraper/drive_metadata.py
- client/scraper/dropbox_metadata.py
- client/scraper/error_metadata.py
- client/scraper/metadata.py
- client/scraper/wikipedia_metadata.py
- client/scraper/youtube_metadata.py
- test/client/scraper/test_wikipedia_metadata.py
- test/client/scraper/test_youtube_metadata.py
#98 
Fixes refactor (had old code without new wikipedia code)
has #104
> Revert "Revert "Remove beautiful soup + refactor metadata code""

- .gitignore
- Makefile
- cache/exceptions.py
- client/api.py
- client/api_handler.py
- client/scraper/error_metadata.py
- client/scraper/metadata.py
- client/scraper/wikipedia_metadata.py
- client/scraper/youtube_metadata.py
- client/url_utils.py
- logs/.gitignore
#76 Added make file, and logger
> Implement logging to file

- README.md
#94 
This is the initial set of proper documentation for Magpie. We can add more as we see fit, but this is the first pass that we should merge to make the Readme look complete.
@AliceYuan @samiyaakhtar @s-varun @avyatwal
> I94 documentation

- CONTRIBUTING.md
> Contribution guide fix

- README.md
- client/api.py
- client/api_handler.py
- client/query_utils.py
> Multiple src queries

- client/api_handler.py
- client/constants.py
- client/scraper/giphy_metadata.py
- client/url_utils.py
- test/client/scraper/test_giphy_metadata.py
> Giphy integration

- .travis.yml
- Makefile
- cache/connection.py
- client/api.py
- client/api_handler.py
- client/cache_utils.py
- client/constants.py
- client/url_utils.py
- config/config.py
- requirements.txt
requires #146 to be merged first
> rate limit code
